import React, { useState } from 'react';
import axios from 'axios';
import { Search, AlertTriangle, CheckCircle, Clock } from 'lucide-react';
import Dashboard from './components/Dashboard.jsx';
import { stripEmoji } from './lib/noEmoji.js';
import './App.css';

// Same-origin /api: proxied to the backend by Vite in dev and by Vercel rewrites in production.
const API = import.meta.env.VITE_API_URL || '/api';

// Results handed over by the landing page scan (see index.html).
function readHandoff() {
  try {
    return stripEmoji(JSON.parse(sessionStorage.getItem('ordo:handoff') || 'null'));
  } catch {
    return null;
  }
}

export default function App() {
  const [handoff] = useState(readHandoff);
  const [repoUrl, setRepoUrl] = useState('');
  const [phase, setPhase] = useState(handoff?.analysis ? 'results' : 'input'); // input | loading | results
  const [loadingMsg, setLoadingMsg] = useState('');
  const [analysisResult, setAnalysisResult] = useState(handoff?.analysis || null);
  const [roadmap, setRoadmap] = useState(handoff?.roadmap || null);
  const [error, setError] = useState(null);

  async function handleAnalyze(e) {
    e.preventDefault();
    if (!repoUrl.trim()) return;
    setError(null);
    setPhase('loading');

    try {
      setLoadingMsg('Fetching repository files…');
      const { data: analysis } = await axios.post(`${API}/analyze`, { repoUrl: repoUrl.trim() });
      setAnalysisResult(stripEmoji(analysis));

      setLoadingMsg('Generating maintenance roadmap…');
      const { data: rm } = await axios.post(`${API}/roadmap`, { analysisResult: analysis });
      setRoadmap(stripEmoji(rm));

      setPhase('results');
    } catch (err) {
      setError(err.response?.data?.error || err.message);
      setPhase('input');
    }
  }

  if (phase === 'results' && analysisResult) {
    return <Dashboard analysis={analysisResult} roadmap={roadmap} onReset={() => {
      try { sessionStorage.removeItem('ordo:handoff'); } catch { /* storage unavailable */ }
      window.location.href = '/';
    }} />;
  }

  return (
    <div className="landing">
      <header className="landing-header">
        <div className="logo">
          <img src="/ordo-logo.png" alt="Ordo" width="1077" height="386" />
        </div>
        <p className="tagline">AI Maintenance Engineer</p>
        <p className="sub-tagline">Identify technical debt, prioritize issues, and generate remediation plans — before problems become expensive.</p>
      </header>

      <form className="analyze-form" onSubmit={handleAnalyze}>
        <div className="input-row">
          <Search size={18} color="var(--muted)" className="input-icon" />
          <input
            type="url"
            value={repoUrl}
            onChange={(e) => setRepoUrl(e.target.value)}
            placeholder="https://github.com/owner/repo"
            disabled={phase === 'loading'}
            className="repo-input"
          />
          <button type="submit" disabled={phase === 'loading' || !repoUrl.trim()} className="analyze-btn">
            {phase === 'loading' ? 'Analyzing…' : 'Analyze'}
          </button>
        </div>
        {error && <p className="error-msg"><AlertTriangle size={14} /> {error}</p>}
      </form>

      {phase === 'loading' && (
        <div className="loading-state">
          <div className="spinner" />
          <p>{loadingMsg}</p>
        </div>
      )}

      <div className="features">
        {[
          { icon: <AlertTriangle size={20} color="var(--red)" />, title: 'Detect Debt', desc: '5 categories: secrets, complexity, coverage, dependencies, documentation' },
          { icon: <CheckCircle size={20} color="var(--green)" />, title: 'Prioritize', desc: 'AI-scored urgency, business impact, and fix effort for every issue' },
          { icon: <Clock size={20} color="var(--accent)" />, title: 'Roadmap', desc: '3-phase maintenance plan generated by watsonx.ai' },
        ].map((f) => (
          <div key={f.title} className="feature-card">
            {f.icon}
            <strong>{f.title}</strong>
            <span>{f.desc}</span>
          </div>
        ))}
      </div>

      <footer className="landing-footer">
        Powered by <strong>watsonx.ai</strong> · ibm/granite-3-8b-instruct · Built for IBM Bob 2.0 Hackathon
      </footer>
    </div>
  );
}
